spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /test_db  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:file:./test_db;AUTO_SERVER=TRUE  #접속 URL
    username: sooyeon  # 사용자 이름 (로그인 시 사용)
    password: sooyeon  # 사용자 암호 (로그인 시 사용)

  resources:
    chain:
      enabled: true
      cache: true
    static-locations: classpath:/static/
    add-mappings: true

  jpa:
    show-sql: true
    truehibernate:
      ddl-auto:
        none properties:
          hibernate:
            format_sql: true

logging:
  level:
    com.kakaobank.webapp.searchplace: debug